name: tensorflow
channels:
  - defaults
dependencies:
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - attrs=21.4.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.2
  - ca-certificates=2022.2.1
  - cffi=1.15.0
  - colorama=0.4.4
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.3
  - icu=58.2
  - importlib_metadata=4.8.2
  - intel-openmp=2021.4.0
  - ipykernel=6.4.1
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.0.2
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=7.1.2
  - jupyter_console=6.4.0
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - libiconv=1.15
  - libpng=1.6.37
  - libxml2=2.9.12
  - libxslt=1.1.34
  - lxml=4.7.1
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nbclient=0.5.11
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - notebook=6.4.8
  - numexpr=2.8.1
  - numpy-base=1.21.5
  - openssl=1.1.1m
  - packaging=21.3
  - pandas=1.4.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=21.2.4
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - pycparser=2.21
  - pygments=2.11.2
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - python=3.9.7
  - python-dateutil=2.8.2
  - pytz=2021.3
  - pywin32=302
  - pywinpty=2.0.2
  - pyzmq=22.3.0
  - qt=5.9.7
  - qtconsole=5.2.2
  - qtpy=1.11.2
  - send2trash=1.8.0
  - sip=4.19.13
  - sqlite=3.37.2
  - terminado=0.13.1
  - testpath=0.5.0
  - tornado=6.1
  - traitlets=5.1.1
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - widgetsnbextension=3.5.2
  - wincertstore=0.2
  - winpty=0.4.3
  - zipp=3.7.0
  - zlib=1.2.11
  - pip:
    - absl-py==0.15.0
    - apache-beam==2.37.0
    - astunparse==1.6.3
    - avro-python3==1.10.2
    - cachetools==5.0.0
    - certifi==2021.10.8
    - charset-normalizer==2.0.12
    - cloudpickle==2.0.0
    - contextlib2==21.6.0
    - crcmod==1.7
    - cycler==0.11.0
    - cython==0.29.28
    - dill==0.3.1.1
    - dm-tree==0.1.6
    - docopt==0.6.2
    - fastavro==1.4.10
    - flatbuffers==1.12
    - fonttools==4.29.1
    - gast==0.4.0
    - gin-config==0.5.0
    - google-api-core==2.6.0
    - google-api-python-client==2.39.0
    - google-auth==2.6.0
    - google-auth-httplib2==0.1.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - googleapis-common-protos==1.55.0
    - grpcio==1.34.1
    - h5py==3.1.0
    - hdfs==2.6.0
    - httplib2==0.19.1
    - idna==3.3
    - importlib-metadata==4.11.2
    - joblib==1.1.0
    - jupyter-http-over-ws==0.0.8
    - kaggle==1.5.12
    - keras==2.8.0
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - libclang==13.0.0
    - lvis==0.5.3
    - markdown==3.3.6
    - matplotlib==3.5.1
    - numpy==1.19.5
    - oauth2client==4.1.3
    - oauthlib==3.2.0
    - object-detection==0.1
    - opencv-python==4.5.5.62
    - opencv-python-headless==4.5.5.62
    - opt-einsum==3.3.0
    - orjson==3.6.7
    - pillow==9.0.1
    - portalocker==2.4.0
    - promise==2.3
    - proto-plus==1.20.3
    - protobuf==3.19.4
    - psutil==5.9.0
    - py-cpuinfo==8.0.0
    - pyarrow==6.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.4
    - pydot==1.4.2
    - pymongo==3.12.3
    - pyparsing==2.4.7
    - python-slugify==6.1.1
    - pyyaml==5.4.1
    - regex==2022.3.2
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - sacrebleu==2.0.0
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - sentencepiece==0.1.96
    - seqeval==1.2.2
    - setuptools==60.9.3
    - six==1.15.0
    - tabulate==0.8.9
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-addons==0.16.1
    - tensorflow-datasets==4.5.2
    - tensorflow-estimator==2.5.0
    - tensorflow-gpu==2.8.0
    - tensorflow-hub==0.12.0
    - tensorflow-io==0.24.0
    - tensorflow-io-gcs-filesystem==0.24.0
    - tensorflow-metadata==1.7.0
    - tensorflow-model-optimization==0.7.1
    - tensorflow-text==2.8.1
    - termcolor==1.1.0
    - text-unidecode==1.3
    - tf-estimator-nightly==2.8.0.dev2021122109
    - tf-models-official==2.8.0
    - tf-slim==1.1.0
    - threadpoolctl==3.1.0
    - tqdm==4.63.0
    - typeguard==2.13.3
    - typing-extensions==3.7.4.3
    - uritemplate==4.1.1
    - urllib3==1.26.8
    - werkzeug==2.0.3
    - wheel==0.37.1
    - wrapt==1.12.1
